use anchor_lang::prelude::*;
use anchor_spl::associated_token::AssociatedToken;
use anchor_spl::token::{self, Mint, Token, TokenAccount, Transfer};

pub mod errors;
pub mod state;

use errors::MaximError;
use state::*;

// Replace with the program ID generated by `anchor keys sync` before deployment.
declare_id!("337JEF6PSMGSPwBSseMHFa95YxLACnJeehA5brVAgzKh");

// ─── Events ───────────────────────────────────────────────────────────────────
//
// Events are emitted on every state-changing instruction and consumed by the
// Maxim Protocol dashboard indexer via Solana's Geyser plugin interface. The
// indexer maintains a one-second lag target; if it falls behind, the dashboard
// instructs users to verify directly via Solana Explorer.

/// Emitted on every successful USDC payment settlement.
#[event]
pub struct PaymentSettled {
    pub agent_wallet: Pubkey,
    pub sequence: u64,
    pub endpoint_hash: [u8; 32],
    pub payee: Pubkey,
    pub amount_usdc: u64,
    /// Protocol discriminant: 0 = x402, 1 = MPP.
    pub protocol: u8,
    pub settled_at: i64,
    pub parent_payment: Option<Pubkey>,
    pub memo: Option<[u8; 32]>,
}

/// Emitted when a payment is rejected by on-chain policy enforcement.
/// No funds are transferred; the record exists for auditability only.
#[event]
pub struct PolicyViolationRecorded {
    pub agent_wallet: Pubkey,
    pub sequence: u64,
    pub endpoint_hash: [u8; 32],
    pub amount_usdc: u64,
    /// Numeric MaximError discriminant identifying the violated constraint.
    pub violation_reason: u8,
}

/// Emitted when an agent wallet is deactivated or reactivated by its owner.
#[event]
pub struct AgentStatusChanged {
    pub agent_wallet: Pubkey,
    pub agent_id: String,
    pub is_active: bool,
    pub changed_at: i64,
}

/// Emitted when the protocol admin freezes or unfreezes an agent wallet.
/// Freeze is independent of the owner-controlled `is_active` flag.
#[event]
pub struct AgentFreezeChanged {
    pub agent_wallet: Pubkey,
    pub agent_id: String,
    pub is_frozen: bool,
    pub changed_at: i64,
}

/// Emitted when USDC is withdrawn from an agent's ATA back to the owner.
#[event]
pub struct FundsWithdrawn {
    pub agent_wallet: Pubkey,
    pub to: Pubkey,
    pub amount_usdc: u64,
    pub withdrawn_at: i64,
}

/// Emitted when ownership of an agent wallet is transferred to a new keypair.
/// Enables KMS key rotation without redeploying.
#[event]
pub struct OwnershipTransferred {
    pub agent_wallet: Pubkey,
    pub old_owner: Pubkey,
    pub new_owner: Pubkey,
    pub transferred_at: i64,
}

/// Emitted whenever a spend policy is created or updated.
/// Captures the new budget and threshold values so the dashboard can display
/// a full audit trail of policy changes without storing pre-update state.
#[event]
pub struct SpendPolicyUpdated {
    pub agent_wallet: Pubkey,
    pub daily_budget: u64,
    pub weekly_budget: u64,
    pub monthly_budget: u64,
    pub per_call_limit: u64,
    pub high_value_threshold: u64,
    pub updated_at: i64,
}

// ─── Instruction Parameters ───────────────────────────────────────────────────

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct SetSpendPolicyParams {
    /// Maximum USDC per 24-hour window (6-decimal fixed-point). Zero = unlimited.
    pub daily_budget: u64,
    /// Maximum USDC per 7-day window (6-decimal fixed-point). Zero = unlimited.
    /// The weekly cap provides a second safety net across multiple daily resets.
    pub weekly_budget: u64,
    /// Maximum USDC per individual payment call (6-decimal). Zero = unlimited.
    pub per_call_limit: u64,
    /// Maximum calls in the rate-limit window. Zero = unlimited.
    pub rate_limit_calls: u32,
    /// Rate-limit window duration in seconds. Ignored when rate_limit_calls is zero.
    pub rate_limit_window_secs: u32,
    /// Minimum USDC amount (6-decimal) that triggers on-chain policy enforcement.
    /// Payments below this threshold rely on gateway enforcement only.
    /// Recommended default: 10_000_000 (10.00 USDC).
    pub high_value_threshold: u64,
    /// Maximum USDC the agent may spend in any 30-day window (6-decimal). Zero = unlimited.
    pub monthly_budget: u64,
    /// SHA-256 hashes of permitted destination domain strings.
    /// Empty = all destinations permitted.
    pub allowed_domain_hashes: Vec<[u8; 32]>,
    /// SHA-256 hashes of explicitly blocked destination domain strings.
    /// Evaluated before the allowlist.
    pub blocked_domain_hashes: Vec<[u8; 32]>,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct SettlePaymentParams {
    /// Agent identifier matching the registered agent_id on the AgentWallet PDA.
    pub agent_id: String,
    /// SHA-256 hash of the full destination endpoint URL.
    /// Stored verbatim in PaymentRecord.endpoint_hash. The full URL is indexed
    /// off-chain (encrypted); only this hash appears on Solana Explorer.
    pub endpoint_hash: [u8; 32],
    /// SHA-256 hash of the bare destination hostname (e.g. SHA256("api.dune.com")).
    /// Used for domain allowlist and blocklist evaluation in SpendPolicy.
    /// Computed by the gateway from the parsed URL host component.
    pub domain_hash: [u8; 32],
    /// USDC amount to transfer (6-decimal fixed-point).
    pub amount_usdc: u64,
    /// Protocol discriminant: 0 = x402, 1 = MPP.
    pub protocol: u8,
    /// Links this payment to a parent in a multi-agent orchestration chain.
    /// Set by the gateway when an orchestrating agent's budget funds a sub-agent run.
    pub parent_payment: Option<Pubkey>,
    /// SHA-256 hash of an arbitrary memo string for off-chain correlation.
    /// Useful for tying a settlement to a workflow ID, job reference, or order number.
    /// Never interpreted on-chain. Set to None when no memo is needed.
    pub memo: Option<[u8; 32]>,
}

// ─── Program ──────────────────────────────────────────────────────────────────

#[program]
pub mod maxim_protocol {
    use super::*;

    /// Initialise the singleton ProtocolConfig account.
    ///
    /// Must be called exactly once by the deployer immediately after deployment.
    /// Sets the protocol admin keypair that will be authorised to freeze and
    /// unfreeze agent wallets via `freeze_agent` / `unfreeze_agent`.
    ///
    /// The `payer` account pays the rent-exempt deposit. In production this is
    /// the Maxim Protocol multisig. The `admin` pubkey may differ from `payer`
    /// — for example, a separate hot-wallet key used only for security operations.
    pub fn init_protocol(ctx: Context<InitProtocol>, admin: Pubkey) -> Result<()> {
        require!(admin != Pubkey::default(), MaximError::InvalidOwner);
        let config = &mut ctx.accounts.protocol_config;
        config.admin = admin;
        config.version = PROGRAM_VERSION;
        config.max_single_payment_usdc = 0; // disabled by default
        config.bump = ctx.bumps.protocol_config;
        Ok(())
    }

    /// Replace the protocol admin keypair stored in ProtocolConfig.
    ///
    /// Only the current admin may rotate to a new admin. This is the path for
    /// planned key rotation; emergency replacement is handled off-chain by
    /// upgrading the program via the upgrade authority.
    pub fn rotate_protocol_admin(
        ctx: Context<RotateProtocolAdmin>,
        new_admin: Pubkey,
    ) -> Result<()> {
        require!(new_admin != Pubkey::default(), MaximError::InvalidOwner);
        ctx.accounts.protocol_config.admin = new_admin;
        Ok(())
    }

    /// Update protocol-level configuration parameters.
    ///
    /// Currently governs `max_single_payment_usdc`, the hard cap on any single
    /// payment settlement across all agent wallets. Setting it to zero disables
    /// the cap. Only the protocol admin may call this.
    ///
    /// This instruction is the primary lever for protocol-wide incident response:
    /// setting a low cap immediately limits further USDC exposure without requiring
    /// individual agent freezes.
    pub fn update_protocol_config(
        ctx: Context<UpdateProtocolConfig>,
        max_single_payment_usdc: u64,
    ) -> Result<()> {
        ctx.accounts.protocol_config.max_single_payment_usdc = max_single_payment_usdc;
        Ok(())
    }

    /// Register a new agent wallet on-chain.
    ///
    /// Creates an AgentWallet PDA scoped to agent_id and initialises its
    /// associated USDC token account. Each agent_id maps to exactly one wallet
    /// address across the entire program. Registration is idempotent at the
    /// account level -- Anchor's init will fail if the PDA already exists.
    ///
    /// The calling owner keypair is recorded as the authorised signer for all
    /// future payment and policy instructions. In production, this keypair is
    /// generated by the SDK and held by the Maxim Protocol KMS under envelope
    /// encryption. It is never transmitted or stored in plaintext.
    pub fn register_agent(ctx: Context<RegisterAgent>, agent_id: String) -> Result<()> {
        require!(
            !agent_id.is_empty() && agent_id.len() <= MAX_AGENT_ID_LEN,
            MaximError::AgentIdTooLong
        );
        require!(
            agent_id.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_'),
            MaximError::InvalidAgentId
        );

        let now = Clock::get()?.unix_timestamp;
        let wallet = &mut ctx.accounts.agent_wallet;

        wallet.agent_id = agent_id;
        wallet.owner = ctx.accounts.owner.key();
        wallet.usdc_token_account = ctx.accounts.usdc_token_account.key();
        wallet.daily_spend = 0;
        wallet.daily_window_start = now;
        wallet.weekly_spend = 0;
        wallet.weekly_window_start = now;
        wallet.monthly_spend = 0;
        wallet.monthly_window_start = now;
        wallet.payment_sequence = 0;
        wallet.last_payment_at = 0;
        wallet.total_payments = 0;
        wallet.total_volume = 0;
        wallet.is_active = true;
        wallet.is_frozen = false;
        wallet.bump = ctx.bumps.agent_wallet;

        Ok(())
    }

    /// Create or update the spend policy for an agent wallet.
    ///
    /// Uses init_if_needed so the same instruction serves both initial creation
    /// and subsequent updates. Only the registered owner keypair may call this.
    ///
    /// Domain hashes must be computed as SHA256(domain_string) where
    /// domain_string is the bare hostname (e.g. "api.dune.com"), not the full URL.
    /// Domain checks are applied in order: blocklist first, then allowlist.
    ///
    /// Setting high_value_threshold to zero disables on-chain policy enforcement
    /// entirely, relying solely on the gateway layer. Setting it to one enforces
    /// every payment on-chain. The recommended default is 10 USDC (10_000_000).
    pub fn set_spend_policy(
        ctx: Context<SetSpendPolicy>,
        params: SetSpendPolicyParams,
    ) -> Result<()> {
        require!(
            params.allowed_domain_hashes.len() <= MAX_DOMAIN_ENTRIES,
            MaximError::DomainListFull
        );
        require!(
            params.blocked_domain_hashes.len() <= MAX_DOMAIN_ENTRIES,
            MaximError::DomainListFull
        );

        let now = Clock::get()?.unix_timestamp;
        let policy = &mut ctx.accounts.spend_policy;

        policy.agent_wallet = ctx.accounts.agent_wallet.key();
        policy.daily_budget = params.daily_budget;
        policy.weekly_budget = params.weekly_budget;
        policy.monthly_budget = params.monthly_budget;
        policy.per_call_limit = params.per_call_limit;
        policy.rate_limit_calls = params.rate_limit_calls;
        policy.rate_limit_window_secs = params.rate_limit_window_secs;
        policy.rate_limit_call_count = 0;
        policy.rate_limit_window_start = now;
        policy.high_value_threshold = params.high_value_threshold;
        policy.allowed_domain_hashes = params.allowed_domain_hashes;
        policy.blocked_domain_hashes = params.blocked_domain_hashes;
        policy.bump = ctx.bumps.spend_policy;

        emit!(SpendPolicyUpdated {
            agent_wallet: ctx.accounts.agent_wallet.key(),
            daily_budget: params.daily_budget,
            weekly_budget: params.weekly_budget,
            monthly_budget: params.monthly_budget,
            per_call_limit: params.per_call_limit,
            high_value_threshold: params.high_value_threshold,
            updated_at: now,
        });

        Ok(())
    }

    /// Settle a completed payment on-chain.
    ///
    /// This is the core settlement instruction. For each payment processed by the
    /// gateway -- whether the upstream protocol was x402 or MPP -- the gateway
    /// constructs and submits this instruction to record the settlement permanently.
    ///
    /// The instruction:
    /// 1. Validates the agent wallet is active and not frozen.
    /// 2. Resets the daily and weekly spend windows if their periods have elapsed.
    /// 3. Enforces spend policy on-chain for payments at or above high_value_threshold.
    /// 4. Transfers USDC from the agent's ATA to the payee's ATA via SPL Token CPI.
    /// 5. Updates wallet accounting state (daily spend, weekly spend, total volume, sequence).
    /// 6. Creates an immutable PaymentRecord on-chain.
    /// 7. Emits a PaymentSettled event for the dashboard indexer.
    ///
    /// The sequence argument must match agent_wallet.payment_sequence at call
    /// time, which is enforced implicitly by the PDA derivation constraint.
    pub fn settle_payment(
        ctx: Context<SettlePayment>,
        sequence: u64,
        params: SettlePaymentParams,
    ) -> Result<()> {
        require!(params.amount_usdc > 0, MaximError::ZeroPaymentAmount);
        require!(
            PaymentProtocol::from_discriminant(params.protocol).is_some(),
            MaximError::InvalidProtocol
        );
        require!(
            sequence == ctx.accounts.agent_wallet.payment_sequence,
            MaximError::SequenceMismatch
        );

        let now = Clock::get()?.unix_timestamp;

        // Protocol-level global cap. Checked first so a single admin action can
        // limit exposure across the entire protocol during an incident.
        {
            let config = &ctx.accounts.protocol_config;
            if config.max_single_payment_usdc > 0 {
                require!(
                    params.amount_usdc <= config.max_single_payment_usdc,
                    MaximError::GlobalPaymentCapExceeded
                );
            }
        }

        // Wallet state guards and window resets.
        {
            let wallet = &mut ctx.accounts.agent_wallet;
            require!(wallet.is_active, MaximError::AgentNotActive);
            require!(!wallet.is_frozen, MaximError::AgentFrozen);
            wallet.reset_daily_window_if_elapsed(now);
            wallet.reset_weekly_window_if_elapsed(now);
            wallet.reset_monthly_window_if_elapsed(now);
        }

        // On-chain policy enforcement (high-value threshold).
        // Payments below high_value_threshold are validated exclusively at the
        // gateway layer. Payments at or above the threshold are additionally
        // validated here, ensuring the on-chain program acts as a second enforcement
        // boundary even if the gateway layer were somehow bypassed.
        {
            let wallet = &ctx.accounts.agent_wallet;
            let policy = &mut ctx.accounts.spend_policy;

            let enforce_on_chain = policy.high_value_threshold > 0
                && params.amount_usdc >= policy.high_value_threshold;

            if enforce_on_chain {
                require!(
                    policy.within_per_call_limit(params.amount_usdc),
                    MaximError::PerCallLimitExceeded
                );
                require!(
                    policy.within_daily_budget(wallet.daily_spend, params.amount_usdc),
                    MaximError::DailyBudgetExceeded
                );
                require!(
                    policy.within_weekly_budget(wallet.weekly_spend, params.amount_usdc),
                    MaximError::WeeklyBudgetExceeded
                );
                require!(
                    policy.within_monthly_budget(wallet.monthly_spend, params.amount_usdc),
                    MaximError::MonthlyBudgetExceeded
                );
                policy.reset_rate_window_if_elapsed(now);
                require!(
                    policy.within_rate_limit(),
                    MaximError::RateLimitExceeded
                );

                // Blocklist is evaluated before allowlist.
                if !policy.blocked_domain_hashes.is_empty() {
                    require!(
                        !policy.blocked_domain_hashes.contains(&params.domain_hash),
                        MaximError::DomainBlocked
                    );
                }

                // Empty allowlist = all destinations permitted.
                if !policy.allowed_domain_hashes.is_empty() {
                    require!(
                        policy.allowed_domain_hashes.contains(&params.domain_hash),
                        MaximError::DomainNotAllowed
                    );
                }

                // Rate limit counter is only incremented for payments that went
                // through on-chain enforcement. Low-value payments (below threshold)
                // do not consume on-chain rate limit quota -- the gateway layer is
                // solely responsible for rate limiting those.
                policy.rate_limit_call_count =
                    policy.rate_limit_call_count.saturating_add(1);
            }
        }

        // SPL Token CPI transfer.
        // The AgentWallet PDA is the authority over its USDC ATA. The PDA signs
        // via invoke_signed using its canonical seeds and bump.
        {
            let agent_id_bytes = ctx.accounts.agent_wallet.agent_id.as_bytes().to_vec();
            let bump = ctx.accounts.agent_wallet.bump;

            let signer_seeds: &[&[&[u8]]] = &[&[
                b"agent_wallet",
                agent_id_bytes.as_slice(),
                &[bump],
            ]];

            token::transfer(
                CpiContext::new_with_signer(
                    ctx.accounts.token_program.to_account_info(),
                    Transfer {
                        from: ctx.accounts.usdc_token_account.to_account_info(),
                        to: ctx.accounts.payee_token_account.to_account_info(),
                        authority: ctx.accounts.agent_wallet.to_account_info(),
                    },
                    signer_seeds,
                ),
                params.amount_usdc,
            )?;
        }

        // Update wallet accounting state.
        {
            let wallet = &mut ctx.accounts.agent_wallet;
            wallet.daily_spend = wallet.daily_spend.saturating_add(params.amount_usdc);
            wallet.weekly_spend = wallet.weekly_spend.saturating_add(params.amount_usdc);
            wallet.monthly_spend = wallet.monthly_spend.saturating_add(params.amount_usdc);
            wallet.total_volume = wallet.total_volume.saturating_add(params.amount_usdc);
            wallet.last_payment_at = now;
            wallet.payment_sequence = wallet.payment_sequence.saturating_add(1);
            wallet.total_payments = wallet.total_payments.saturating_add(1);
        }

        let payee_pubkey = ctx.accounts.payee_token_account.owner;

        // Write immutable PaymentRecord.
        let record = &mut ctx.accounts.payment_record;
        record.agent_wallet = ctx.accounts.agent_wallet.key();
        record.sequence = sequence;
        record.endpoint_hash = params.endpoint_hash;
        record.payee = payee_pubkey;
        record.amount_usdc = params.amount_usdc;
        record.protocol = PaymentProtocol::from_discriminant(params.protocol).unwrap();
        record.settled_at = now;
        record.policy_passed = true;
        record.parent_payment = params.parent_payment;
        record.memo = params.memo;
        record.bump = ctx.bumps.payment_record;

        emit!(PaymentSettled {
            agent_wallet: ctx.accounts.agent_wallet.key(),
            sequence,
            endpoint_hash: params.endpoint_hash,
            payee: payee_pubkey,
            amount_usdc: params.amount_usdc,
            protocol: params.protocol,
            settled_at: now,
            parent_payment: params.parent_payment,
            memo: params.memo,
        });

        Ok(())
    }

    /// Record a policy violation on-chain without executing a transfer.
    ///
    /// Called by the gateway when a payment is rejected at the gateway policy layer
    /// and the rejection should be permanently auditable on-chain. No USDC is moved.
    /// The resulting PaymentRecord has policy_passed = false, distinguishing it
    /// from successful settlements in ledger queries.
    ///
    /// Finance and security teams can use violation records to audit attempted
    /// overspend, domain bypass attempts, or rate-limit breaches without relying
    /// on off-chain log infrastructure.
    pub fn record_policy_violation(
        ctx: Context<RecordPolicyViolation>,
        sequence: u64,
        params: SettlePaymentParams,
        violation_reason: u8,
    ) -> Result<()> {
        require!(
            PaymentProtocol::from_discriminant(params.protocol).is_some(),
            MaximError::InvalidProtocol
        );
        require!(
            sequence == ctx.accounts.agent_wallet.payment_sequence,
            MaximError::SequenceMismatch
        );

        let now = Clock::get()?.unix_timestamp;

        {
            let wallet = &mut ctx.accounts.agent_wallet;
            wallet.payment_sequence = wallet.payment_sequence.saturating_add(1);
            wallet.total_payments = wallet.total_payments.saturating_add(1);
        }

        let record = &mut ctx.accounts.payment_record;
        record.agent_wallet = ctx.accounts.agent_wallet.key();
        record.sequence = sequence;
        record.endpoint_hash = params.endpoint_hash;
        record.payee = Pubkey::default();
        record.amount_usdc = params.amount_usdc;
        record.protocol = PaymentProtocol::from_discriminant(params.protocol).unwrap();
        record.settled_at = now;
        record.policy_passed = false;
        record.parent_payment = None;
        record.memo = params.memo;
        record.bump = ctx.bumps.payment_record;

        emit!(PolicyViolationRecorded {
            agent_wallet: ctx.accounts.agent_wallet.key(),
            sequence,
            endpoint_hash: params.endpoint_hash,
            amount_usdc: params.amount_usdc,
            violation_reason,
        });

        Ok(())
    }

    /// Deactivate an agent wallet.
    ///
    /// Once deactivated, all settle_payment calls targeting this wallet are
    /// rejected by the program. The agent's USDC remains in its ATA and is
    /// accessible via `withdraw_funds` or any Solana wallet that holds the
    /// agent keypair.
    ///
    /// Only the registered owner keypair may deactivate. Deactivation is
    /// reversible via reactivate_agent.
    pub fn deactivate_agent(ctx: Context<ManageAgentStatus>) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        let wallet_key = ctx.accounts.agent_wallet.key();
        let agent_id = {
            let wallet = &mut ctx.accounts.agent_wallet;
            let id = wallet.agent_id.clone();
            wallet.is_active = false;
            id
        };

        emit!(AgentStatusChanged {
            agent_wallet: wallet_key,
            agent_id,
            is_active: false,
            changed_at: now,
        });

        Ok(())
    }

    /// Reactivate a previously deactivated agent wallet.
    ///
    /// Only the registered owner keypair may reactivate.
    pub fn reactivate_agent(ctx: Context<ManageAgentStatus>) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        let wallet_key = ctx.accounts.agent_wallet.key();
        let agent_id = {
            let wallet = &mut ctx.accounts.agent_wallet;
            let id = wallet.agent_id.clone();
            wallet.is_active = true;
            id
        };

        emit!(AgentStatusChanged {
            agent_wallet: wallet_key,
            agent_id,
            is_active: true,
            changed_at: now,
        });

        Ok(())
    }

    /// Freeze an agent wallet at the protocol level.
    ///
    /// Only the `ProtocolConfig.admin` keypair may call this. Freezing is
    /// independent of the owner-controlled `is_active` flag and is intended
    /// for security incident response. A frozen wallet cannot process payments
    /// but its owner can still call `withdraw_funds` to recover USDC, preserving
    /// the non-custodial guarantee.
    pub fn freeze_agent(ctx: Context<ProtocolManageAgent>) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        let wallet_key = ctx.accounts.agent_wallet.key();
        let agent_id = {
            let wallet = &mut ctx.accounts.agent_wallet;
            let id = wallet.agent_id.clone();
            wallet.is_frozen = true;
            id
        };

        emit!(AgentFreezeChanged {
            agent_wallet: wallet_key,
            agent_id,
            is_frozen: true,
            changed_at: now,
        });

        Ok(())
    }

    /// Unfreeze a previously frozen agent wallet.
    ///
    /// Only the `ProtocolConfig.admin` keypair may call this.
    pub fn unfreeze_agent(ctx: Context<ProtocolManageAgent>) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        let wallet_key = ctx.accounts.agent_wallet.key();
        let agent_id = {
            let wallet = &mut ctx.accounts.agent_wallet;
            let id = wallet.agent_id.clone();
            wallet.is_frozen = false;
            id
        };

        emit!(AgentFreezeChanged {
            agent_wallet: wallet_key,
            agent_id,
            is_frozen: false,
            changed_at: now,
        });

        Ok(())
    }

    /// Withdraw USDC from an agent's ATA to an owner-controlled token account.
    ///
    /// This is the primary path for reclaiming funds after deactivating an agent,
    /// winding down an orchestration workflow, or responding to a protocol freeze.
    /// Critically, `withdraw_funds` succeeds regardless of `is_active` or `is_frozen`
    /// state -- the registered owner can always recover their USDC.
    ///
    /// The `owner_token_account` must be a USDC ATA whose owner matches the
    /// AgentWallet's registered `owner` keypair. Anchor verifies this via the
    /// `associated_token::authority = owner` constraint.
    pub fn withdraw_funds(ctx: Context<WithdrawFunds>, amount: u64) -> Result<()> {
        require!(amount > 0, MaximError::ZeroPaymentAmount);
        require!(
            ctx.accounts.usdc_token_account.amount >= amount,
            MaximError::InsufficientFunds
        );

        let now = Clock::get()?.unix_timestamp;
        let agent_id = ctx.accounts.agent_wallet.agent_id.clone();
        let bump = ctx.accounts.agent_wallet.bump;

        cpi_transfer_from_wallet(
            ctx.accounts.token_program.to_account_info(),
            ctx.accounts.usdc_token_account.to_account_info(),
            ctx.accounts.owner_token_account.to_account_info(),
            ctx.accounts.agent_wallet.to_account_info(),
            &agent_id,
            bump,
            amount,
        )?;

        emit!(FundsWithdrawn {
            agent_wallet: ctx.accounts.agent_wallet.key(),
            to: ctx.accounts.owner_token_account.owner,
            amount_usdc: amount,
            withdrawn_at: now,
        });

        Ok(())
    }

    /// Transfer ownership of an agent wallet to a new keypair.
    ///
    /// The current owner signs the instruction; after this call, the new owner
    /// is the only keypair that can authorise payment, policy, and withdrawal
    /// instructions. The old owner keypair is immediately revoked.
    ///
    /// This is the on-chain path for KMS key rotation. The Maxim Protocol
    /// dashboard uses this instruction when a key rotation event is detected
    /// in the KMS audit log.
    pub fn transfer_ownership(
        ctx: Context<TransferOwnership>,
        new_owner: Pubkey,
    ) -> Result<()> {
        require!(new_owner != Pubkey::default(), MaximError::InvalidOwner);
        require!(new_owner != ctx.accounts.agent_wallet.owner, MaximError::OwnerUnchanged);

        let now = Clock::get()?.unix_timestamp;
        let wallet_key = ctx.accounts.agent_wallet.key();
        let old_owner = ctx.accounts.agent_wallet.owner;

        ctx.accounts.agent_wallet.owner = new_owner;

        emit!(OwnershipTransferred {
            agent_wallet: wallet_key,
            old_owner,
            new_owner,
            transferred_at: now,
        });

        Ok(())
    }

    /// Permanently close an agent wallet and its spend policy, reclaiming rent.
    ///
    /// Requirements:
    /// - The wallet must already be deactivated (via `deactivate_agent`).
    /// - The agent's USDC token account must be fully drained (via `withdraw_funds`
    ///   or `withdraw_all`) before calling this instruction.
    ///
    /// On success, Anchor's `close` constraint transfers the lamports from both
    /// the `agent_wallet` and `spend_policy` accounts to the owner, zeroing the
    /// accounts and permanently removing them from the ledger.
    pub fn close_agent(_ctx: Context<CloseAgent>) -> Result<()> {
        Ok(())
    }

    /// Withdraw the entire USDC balance from an agent's ATA in a single call.
    ///
    /// Convenience wrapper around `withdraw_funds` that derives the amount
    /// automatically from the current ATA balance, avoiding a prefetch round-trip.
    /// Succeeds regardless of `is_active` or `is_frozen` state.
    pub fn withdraw_all(ctx: Context<WithdrawFunds>) -> Result<()> {
        let amount = ctx.accounts.usdc_token_account.amount;
        require!(amount > 0, MaximError::ZeroPaymentAmount);

        let now = Clock::get()?.unix_timestamp;
        let agent_id = ctx.accounts.agent_wallet.agent_id.clone();
        let bump = ctx.accounts.agent_wallet.bump;

        cpi_transfer_from_wallet(
            ctx.accounts.token_program.to_account_info(),
            ctx.accounts.usdc_token_account.to_account_info(),
            ctx.accounts.owner_token_account.to_account_info(),
            ctx.accounts.agent_wallet.to_account_info(),
            &agent_id,
            bump,
            amount,
        )?;

        emit!(FundsWithdrawn {
            agent_wallet: ctx.accounts.agent_wallet.key(),
            to: ctx.accounts.owner_token_account.owner,
            amount_usdc: amount,
            withdrawn_at: now,
        });

        Ok(())
    }
}

fn cpi_transfer_from_wallet<'info>(
    token_program: AccountInfo<'info>,
    from: AccountInfo<'info>,
    to: AccountInfo<'info>,
    authority: AccountInfo<'info>,
    agent_id: &str,
    bump: u8,
    amount: u64,
) -> Result<()> {
    let agent_id_bytes = agent_id.as_bytes();
    let bump_ref = &[bump];
    let signer_seeds: &[&[&[u8]]] = &[&[b"agent_wallet", agent_id_bytes, bump_ref]];
    token::transfer(
        CpiContext::new_with_signer(
            token_program,
            Transfer { from, to, authority },
            signer_seeds,
        ),
        amount,
    )
}

// ─── Account Contexts ─────────────────────────────────────────────────────────

#[derive(Accounts)]
pub struct InitProtocol<'info> {
    /// Singleton ProtocolConfig PDA. Initialised once; Anchor's `init` constraint
    /// prevents a second call by failing if the account already exists.
    #[account(
        init,
        payer = payer,
        space = ProtocolConfig::LEN,
        seeds = [b"protocol_config"],
        bump,
    )]
    pub protocol_config: Account<'info, ProtocolConfig>,

    #[account(mut)]
    pub payer: Signer<'info>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct RotateProtocolAdmin<'info> {
    #[account(
        mut,
        seeds = [b"protocol_config"],
        bump = protocol_config.bump,
        has_one = admin @ MaximError::Unauthorized,
    )]
    pub protocol_config: Account<'info, ProtocolConfig>,

    pub admin: Signer<'info>,
}

#[derive(Accounts)]
pub struct UpdateProtocolConfig<'info> {
    #[account(
        mut,
        seeds = [b"protocol_config"],
        bump = protocol_config.bump,
        has_one = admin @ MaximError::Unauthorized,
    )]
    pub protocol_config: Account<'info, ProtocolConfig>,

    pub admin: Signer<'info>,
}

#[derive(Accounts)]
#[instruction(agent_id: String)]
pub struct RegisterAgent<'info> {
    /// The AgentWallet PDA. Derived from [b"agent_wallet", agent_id.as_bytes()].
    /// Created and owned by this program. The PDA is the authority over usdc_token_account.
    #[account(
        init,
        payer = owner,
        space = AgentWallet::LEN,
        seeds = [b"agent_wallet", agent_id.as_bytes()],
        bump,
    )]
    pub agent_wallet: Account<'info, AgentWallet>,

    /// The USDC associated token account owned by the AgentWallet PDA.
    /// Created here; funded separately via direct transfer or the dashboard.
    #[account(
        init,
        payer = owner,
        associated_token::mint = usdc_mint,
        associated_token::authority = agent_wallet,
    )]
    pub usdc_token_account: Account<'info, TokenAccount>,

    /// The USDC SPL Token mint. Must match the deployed USDC mint address for
    /// the target network (mainnet: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v).
    pub usdc_mint: Account<'info, Mint>,

    /// The agent's owner keypair. Pays for account rent and is recorded as the
    /// authorised signer for all future instructions on this wallet.
    #[account(mut)]
    pub owner: Signer<'info>,

    pub token_program: Program<'info, Token>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>,
}

#[derive(Accounts)]
pub struct SetSpendPolicy<'info> {
    /// The SpendPolicy PDA for this agent. Derived from [b"spend_policy", agent_wallet].
    /// init_if_needed handles both initial creation and subsequent updates.
    #[account(
        init_if_needed,
        payer = owner,
        space = SpendPolicy::LEN,
        seeds = [b"spend_policy", agent_wallet.key().as_ref()],
        bump,
    )]
    pub spend_policy: Account<'info, SpendPolicy>,

    /// The target agent wallet. Must have owner matching the instruction signer.
    #[account(has_one = owner @ MaximError::Unauthorized)]
    pub agent_wallet: Account<'info, AgentWallet>,

    #[account(mut)]
    pub owner: Signer<'info>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(sequence: u64, params: SettlePaymentParams)]
pub struct SettlePayment<'info> {
    /// The immutable PaymentRecord created by this instruction.
    /// PDA seeds include the sequence number so each payment maps to a unique address,
    /// and the full ledger is independently derivable from agent wallet + sequence.
    #[account(
        init,
        payer = owner,
        space = PaymentRecord::LEN,
        seeds = [
            b"payment_record",
            agent_wallet.key().as_ref(),
            &sequence.to_le_bytes(),
        ],
        bump,
    )]
    pub payment_record: Account<'info, PaymentRecord>,

    /// The originating agent wallet. Derived from [b"agent_wallet", params.agent_id]
    /// so Anchor verifies the PDA matches before executing the instruction body.
    /// has_one = owner ensures only the registered keypair can submit payments.
    #[account(
        mut,
        seeds = [b"agent_wallet", params.agent_id.as_bytes()],
        bump = agent_wallet.bump,
        has_one = owner @ MaximError::Unauthorized,
    )]
    pub agent_wallet: Account<'info, AgentWallet>,

    /// The active spend policy for this agent.
    /// Required so on-chain enforcement runs for high-value payments.
    #[account(
        mut,
        seeds = [b"spend_policy", agent_wallet.key().as_ref()],
        bump = spend_policy.bump,
        constraint = spend_policy.agent_wallet == agent_wallet.key(),
    )]
    pub spend_policy: Account<'info, SpendPolicy>,

    /// The agent's USDC ATA. Source of the SPL Token transfer.
    #[account(
        mut,
        associated_token::mint = usdc_mint,
        associated_token::authority = agent_wallet,
    )]
    pub usdc_token_account: Account<'info, TokenAccount>,

    /// The payee's USDC token account. Destination of the SPL Token transfer.
    #[account(mut)]
    pub payee_token_account: Account<'info, TokenAccount>,

    pub usdc_mint: Account<'info, Mint>,

    /// The agent's registered owner keypair, held by the Maxim Protocol KMS.
    /// This signature authorises the payment and the on-chain record creation.
    #[account(mut)]
    pub owner: Signer<'info>,

    /// The singleton protocol configuration. Read to enforce the global payment cap.
    #[account(
        seeds = [b"protocol_config"],
        bump = protocol_config.bump,
    )]
    pub protocol_config: Account<'info, ProtocolConfig>,

    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(sequence: u64, params: SettlePaymentParams)]
pub struct RecordPolicyViolation<'info> {
    /// The violation record. Same PDA scheme as successful payment records;
    /// distinguished by payment_record.policy_passed == false.
    #[account(
        init,
        payer = owner,
        space = PaymentRecord::LEN,
        seeds = [
            b"payment_record",
            agent_wallet.key().as_ref(),
            &sequence.to_le_bytes(),
        ],
        bump,
    )]
    pub payment_record: Account<'info, PaymentRecord>,

    #[account(
        mut,
        seeds = [b"agent_wallet", params.agent_id.as_bytes()],
        bump = agent_wallet.bump,
        has_one = owner @ MaximError::Unauthorized,
    )]
    pub agent_wallet: Account<'info, AgentWallet>,

    #[account(mut)]
    pub owner: Signer<'info>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct ManageAgentStatus<'info> {
    #[account(
        mut,
        has_one = owner @ MaximError::Unauthorized,
    )]
    pub agent_wallet: Account<'info, AgentWallet>,

    pub owner: Signer<'info>,
}

/// Used by `freeze_agent` and `unfreeze_agent`. Requires the protocol admin to sign.
#[derive(Accounts)]
pub struct ProtocolManageAgent<'info> {
    #[account(mut)]
    pub agent_wallet: Account<'info, AgentWallet>,

    #[account(
        seeds = [b"protocol_config"],
        bump = protocol_config.bump,
        has_one = admin @ MaximError::Unauthorized,
    )]
    pub protocol_config: Account<'info, ProtocolConfig>,

    pub admin: Signer<'info>,
}

#[derive(Accounts)]
pub struct WithdrawFunds<'info> {
    /// The agent wallet whose ATA is being drained. Verified via has_one = owner
    /// so only the registered keypair can authorise withdrawals.
    #[account(
        has_one = owner @ MaximError::Unauthorized,
    )]
    pub agent_wallet: Account<'info, AgentWallet>,

    /// The agent's USDC ATA. Source of the withdrawal transfer.
    #[account(
        mut,
        associated_token::mint = usdc_mint,
        associated_token::authority = agent_wallet,
    )]
    pub usdc_token_account: Account<'info, TokenAccount>,

    /// The owner's USDC ATA. Destination of the withdrawal. The
    /// `associated_token::authority = owner` constraint ensures funds can only
    /// flow to an account the owner controls.
    #[account(
        mut,
        associated_token::mint = usdc_mint,
        associated_token::authority = owner,
    )]
    pub owner_token_account: Account<'info, TokenAccount>,

    pub usdc_mint: Account<'info, Mint>,

    pub owner: Signer<'info>,

    pub token_program: Program<'info, Token>,
    pub associated_token_program: Program<'info, AssociatedToken>,
}

#[derive(Accounts)]
pub struct TransferOwnership<'info> {
    /// The wallet whose ownership is being transferred. has_one = owner ensures
    /// only the current registered keypair can initiate the transfer.
    #[account(
        mut,
        has_one = owner @ MaximError::Unauthorized,
    )]
    pub agent_wallet: Account<'info, AgentWallet>,

    pub owner: Signer<'info>,
}

#[derive(Accounts)]
pub struct CloseAgent<'info> {
    /// The wallet to close. Must be deactivated and have an empty ATA.
    /// Anchor's `close = owner` transfers its rent lamports to the owner.
    #[account(
        mut,
        close = owner,
        has_one = owner @ MaximError::Unauthorized,
        constraint = !agent_wallet.is_active @ MaximError::AgentStillActive,
    )]
    pub agent_wallet: Account<'info, AgentWallet>,

    /// The spend policy PDA associated with this wallet. Closed alongside the wallet
    /// so rent is fully reclaimed in one transaction.
    #[account(
        mut,
        close = owner,
        seeds = [b"spend_policy", agent_wallet.key().as_ref()],
        bump = spend_policy.bump,
    )]
    pub spend_policy: Account<'info, SpendPolicy>,

    /// The agent's USDC ATA. Must be fully drained before the wallet can be closed.
    #[account(
        associated_token::mint = usdc_mint,
        associated_token::authority = agent_wallet,
        constraint = usdc_token_account.amount == 0 @ MaximError::TokenAccountNotEmpty,
    )]
    pub usdc_token_account: Account<'info, TokenAccount>,

    pub usdc_mint: Account<'info, Mint>,

    #[account(mut)]
    pub owner: Signer<'info>,

    pub token_program: Program<'info, Token>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
}
